ngpu: 1

dataset:
  num_classes: 8
  training:
    csi_info_path: dataset/annotations/val_video_info.csv
    csi_anno_path: dataset/annotations/val_Annotation_ours.csv
    csi_data_path: ./dataset/smartwifi/validation_npy/
    clip_length: 4096
    clip_stride: 2000
    
  testing:
    csi_info_path: dataset/annotations/test_video_info.csv
    csi_anno_path: dataset/annotations/test_Annotation_ours.csv
    csi_data_path: ./dataset/smartwifi/test_npy/
    clip_length: 4096
    clip_stride: 2000
    
model:
  name: TALFi
  in_channels: 60

training:
  batch_size: 6
  learning_rate: 4e-5
  weight_decay: 1e-3
  max_epoch: 40
  focal_loss: true
  checkpoint_path: ./cache/
  random_seed: 2020

testing:
  conf_thresh: 0.01
  top_k: 250
  nms_thresh: 0.5
  nms_sigma: 0.95
  checkpoint_path: ./cache/
  output_path: ./output/

evaling:
  gt_json: ./dataset/annotations/gt.json
